### ISSUE TITLE
Add local paths

### ISSUE THREAD

**Issue by seifreed** [EFForg/yaya#22] opened 2021-01-12 19:26 UTC
Actually, it's only possible to add GIT repositories.

Sometimes, you will have either private GitHub repositories or a local path with rules. 

It's possible to add the possibility to add local paths?

**Comment by cooperq** [comment] 2021-02-16 20:14
I would love to have this feature, but I don't currently have the time to add it myself. Closing as a duplicate of #8

**Closed as completed by cooperq** 2021-02-16 20:14 UTC
